### ISSUE TITLE
Having issue with implementation.

### ISSUE THREAD

**Issue by akatrodiya** [ssbc/emoji-server#1]
I downloaded this to integrate Emogi into my website.
I'm sorry.. but I could not understand, How to integrate this module into my website.. can you explain me little bit?

**Comment by dominictarr** [comment]
this just creates a http server for: https://www.npmjs.com/package/emoji-named-characters

if you site then has tags like `<img src=/emoji/+1.png>` then emoji will be requested.
we used a fork of marked with emoji support https://github.com/ssbc/marked
and a suggest-box https://github.com/pfraze/suggest-box popup to allow people to post emoji (works just like on github)
:hamburger:

**Comment by akatrodiya** [comment]
Thank you very much.. I understood now.

On Sun, Jul 3, 2016 at 5:06 AM, Dominic Tarr notifications@github.com
wrote:

> this just creates a http server for:
> https://www.npmjs.com/package/emoji-named-characters
> 
> if you site then has tags like <img src=/emoji/+1.png> then emoji will be
> requested.
> we used a fork of marked with emoji support https://github.com/ssbc/marked
> and a suggest-box popup to allow people to post emoji (works just like on
> github)
> 🍔
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ssbc/emoji-server/issues/1#issuecomment-230127269,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOVJHy_kRo2KPCdvyygsWjKtMVZbRrAfks5qRvYCgaJpZM4JDpBO
> .

## 

_Ajay Katrodiya_
CEO at Aarya Solution.
M - +91 9662100694
E - ajaykatrodiya@gmail.com
